export const appActions = {
  //Authentication
  GET_USER: "GET_USER",
  LOGIN: "LOGIN",
  SIGN_UP: "SIGN_UP",
  FORGET_PASSWORD: "FORGET_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  LOGOUT: "LOGOUT",
  GENERATE_PAYMENT_LINK:"GENERATE_PAYMENT_LINK"
};
