export const appActions = {
  //Authentication
  GET_USER: "GET_USER",
  LOGIN: "LOGIN",
  SIGN_UP: "SIGN_UP",
  FORGET_PASSWORD: "FORGET_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  LOGOUT: "LOGOUT",
  GENERATE_PAYMENT_LINK:"GENERATE_PAYMENT_LINK",
  VERIFY_PAYMENT_STATUS:"VERIFY_PAYMENT_STATUS",
  SAVE_LAND:"SAVE_LAND",
  GET_LAND:"GET_LAND",
  UPDATE_LAND:"UPDATE_LAND",
  DELETE_LAND:"DELETE_LAND",
  UPLOAD_SINGLE_IMAGE:"UPLOAD_SINGLE_IMAGE"
};
